apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: nephio-webui-role-binding
  namespace: default
subjects:
- kind: ServiceAccount
  name: nephio-webui-sa
  namespace: nephio-webui
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: ""
